name: Streamlit App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Specify the version of Python you're using

      - name: Install dependencies
        run: pip install -r requirements.txt  # Replace with the path to your requirements.txt file

      - name: Run Streamlit app
        run: streamlit run your_app.py  # Replace with the name of your Streamlit app file
